### ISSUE TITLE
OCR correction is not being saved in certain cases

### ISSUE THREAD

**Issue by snmnzl** [qurator-spk/neath#35] opened 2019-12-09 16:10 UTC
We noticed that OCR corrections in combinations of strings with punctuations are not being saved (e.g. "31.") even if they were corrected several times.

**Comment by cneud** [comment] 2019-12-16 14:44
fixed in a1bd8afc9dd764c87c24992143632b9aa11b3d07 (cannot reproduce anymore)

**Comment by snmnzl** [comment] 2019-12-19 10:44
Thank you for the fix, the number-punctuation-examples are being saved now and do show when opening the file with Excel or Notepad++ after saving. However, re-opening the saved file in neath does not show the aforementioned corrections (tried on Firefox and Chrome). Example: Donnerstag, **1.** Januar)

**Comment by labusch** [comment] 2019-12-19 13:53
Right, this bug is a funny one.
The CSV parser (papaparse) interprets the string "1." as a floating point number, i.e., 1.0. 
I'll see how to fix it.

**Closed** 2019-12-19 14:03 UTC
Labels: bug
